### ISSUE TITLE
Allow caching of POST requests based on form data

### ISSUE THREAD

**Issue by njt1982** [dobs/faraday-manual-cache#1]
I have a use case where I POST to an API for search results. I'd like to cache the POST, but:

a) This caches GET/HEAD only
b) It only considers the URL, not any POST data

**Comment by dobs** [comment]
Two options come to mind:

1. Add a configuration option for specifying which HTTP verbs to cache. This is the simplest, but difficult to work with if using both cacheable and uncacheable POST requests.
2. Add support for `Cache-Control` as a request header. More complicated both to implement and use, but provides much more control.

Thoughts, based on your use case?

**Comment by njt1982** [comment]
Could we expose the `cacheable?` method somehow, maybe via a lamba function in the options?

We would call the lambda method and if it returns true/false then obey that otherwise use the internal check (eg if it returns nil)?

I can understand not wanting to add `:post` to the list as if you were POSTing to a REST API to create a new "thing", that is certainly not cachable! :)

**Comment by dobs** [comment]
I like the lambda idea -- I'll have a PR up with that by end of day!

And yep, fear of breaking POST expectations is why I avoided including it (along with PUT, PATCH, etc.), but I should have made this behaviour customizable.

**Comment by dobs** [comment]
Added with #2: Middleware now supports a `conditions` option. All HTTP verbs can be supported with something like the following:

```ruby
builder.use :manual_cache, conditions: ->(env) { true }, ...
```
